pipeline {
    agent any

    environment {
        XYML_CI = '1'

        RELEASE_CHANNEL = 'beta'
        MICROSOFT_AUTH_ID = credentials('microsoft_auth_id')
        CURSEFORGE_API_KEY = credentials('curseforge_api_key')
        XYML_SIGNATURE_KEY = credentials('xyml_signature_key')
    }

    stages {
        stage('Build') {
            steps {
                sh 'bash ./config/jenkins/config-jenkins.sh'
                sh './gradlew clean makeExecutables makeDeb --stacktrace --no-daemon'
                archiveArtifacts artifacts: 'XYML/build/libs/*'
            }
        }
    }
}
