import java.io.DataInputStream
import java.util.jar.JarFile

plugins {
    `java-library`
}

group = "space.minecraftstl.xyml"
version = rootProject.extra["xymlReleaseVersion"] as String
description = "XYML's namespaced fork of lwjgl-unsafe-agent."

base {
    archivesName.set("lwjgl-unsafe-agent")
}

dependencies {
    compileOnly(libs.jetbrains.annotations)
    testImplementation(libs.jetbrains.annotations)
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(25))
    withSourcesJar()
    withJavadocJar()
}

val agentClassName = "space.minecraftstl.xyml.library.lwjgl.UnsafeAgent"
val upstreamVersion = "2.0"
val generatedBuildConfigDirectory = layout.buildDirectory.dir("generated/sources/buildConfig/java/main")
val generatedBuildConfigFile = generatedBuildConfigDirectory.map {
    it.file("space/minecraftstl/xyml/library/lwjgl/BuildConfig.java")
}

val generateBuildConfig = tasks.register("generateBuildConfig") {
    description = "Generates version constants for the namespaced agent."
    inputs.property("projectVersion", project.version.toString())
    inputs.property("upstreamVersion", upstreamVersion)
    outputs.file(generatedBuildConfigFile)

    doLast {
        val outputFile = generatedBuildConfigFile.get().asFile
        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            """
            /*
             * Copyright 2026 MinecraftSTL
             *
             * Licensed under the Apache License, Version 2.0 (the "License");
             * you may not use this file except in compliance with the License.
             * You may obtain a copy of the License at
             *
             *     http://www.apache.org/licenses/LICENSE-2.0
             *
             * Unless required by applicable law or agreed to in writing, software
             * distributed under the License is distributed on an "AS IS" BASIS,
             * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
             * See the License for the specific language governing permissions and
             * limitations under the License.
             */
            // Added by MinecraftSTL in 2026 for the XYML namespace and monorepo build.
            package space.minecraftstl.xyml.library.lwjgl;

            import org.jetbrains.annotations.NotNullByDefault;

            /// Provides build versions generated by the root XYML build.
            @NotNullByDefault
            public final class BuildConfig {
                /// XYML release version used by the independently published agent artifact.
                public static final String PROJECT_VERSION = "${project.version}";

                /// Locked upstream lwjgl-unsafe-agent version represented by this fork.
                public static final String UPSTREAM_VERSION = "$upstreamVersion";

                /// Prevents instantiation of this constants class.
                private BuildConfig() {
                }
            }
            """.trimIndent() + "\n",
            Charsets.UTF_8,
        )
    }
}

sourceSets.main {
    java.srcDir(generatedBuildConfigDirectory)
}

tasks.withType<JavaCompile> {
    options.release.set(25)
}

tasks.compileJava {
    dependsOn(generateBuildConfig)
}

tasks.named("sourcesJar") {
    dependsOn(generateBuildConfig)
}

tasks.javadoc {
    dependsOn(generateBuildConfig)
    (options as StandardJavadocDocletOptions).also {
        it.jFlags!!.addAll(listOf("-Duser.language=en", "-Duser.country=", "-Duser.variant="))
        it.encoding("UTF-8")
        it.addStringOption("link", "https://docs.oracle.com/en/java/javase/25/docs/api/")
        it.addBooleanOption("html5", true)
        it.addStringOption("Xdoclint:none", "-quiet")
    }
}

tasks.jar {
    manifest.attributes(
        "Premain-Class" to agentClassName,
        "Agent-Class" to agentClassName,
        "Automatic-Module-Name" to "space.minecraftstl.xyml.library.lwjgl",
        "Implementation-Version" to project.version.toString(),
        "Lwjgl-Unsafe-Agent-Upstream-Version" to upstreamVersion,
    )
}

tasks.test {
    dependsOn(tasks.jar)
    doFirst {
        systemProperty("xyml.lwjglUnsafeAgent.jar", tasks.jar.get().archiveFile.get().asFile.absolutePath)
        systemProperty("xyml.lwjglUnsafeAgent.testClasspath", sourceSets.test.get().runtimeClasspath.asPath)
    }
}

tasks.withType<GenerateModuleMetadata> {
    enabled = false
}

publishing {
    publications.named<MavenPublication>("maven") {
        artifactId = "lwjgl-unsafe-agent"
        pom {
            name.set("lwjgl-unsafe-agent")
            description.set(project.description)
            url.set("https://github.com/MinecraftSTL/XYML/tree/dev/libraries/lwjgl-unsafe-agent")
            licenses {
                license {
                    name.set("Apache License 2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0")
                }
            }
            developers {
                developer {
                    id.set("glavo")
                    name.set("Glavo")
                    email.set("zjx001202@gmail.com")
                }
            }
            scm {
                url.set("https://github.com/MinecraftSTL/XYML")
            }
        }
    }
}

val agentJavaFiles = fileTree("src") {
    include("**/*.java")
}

val verifyAgentLicenseHeaders = tasks.register("verifyAgentLicenseHeaders") {
    group = "verification"
    description = "Verifies preserved Apache-2.0 headers and XYML modification notices."
    inputs.files(agentJavaFiles)

    doLast {
        agentJavaFiles.files.sorted().forEach { sourceFile ->
            val source = sourceFile.readText(Charsets.UTF_8)
            val preamble = source.substring(0, minOf(source.length, 1_500))
            check("Licensed under the Apache License, Version 2.0" in preamble) {
                "Missing preserved Apache-2.0 license in $sourceFile"
            }
            check("Copyright" in preamble) { "Missing preserved copyright in $sourceFile" }
            check("Modified by MinecraftSTL" in preamble || "Added by MinecraftSTL" in preamble) {
                "Missing XYML modification notice in $sourceFile"
            }
        }
    }
}

val verifyAgentArtifact = tasks.register("verifyAgentArtifact") {
    group = "verification"
    description = "Verifies the agent manifest, package identity, version metadata, and Java 25 bytecode."
    dependsOn(tasks.jar)
    val archiveFile = tasks.jar.flatMap { it.archiveFile }
    inputs.file(archiveFile)

    doLast {
        JarFile(archiveFile.get().asFile).use { jar ->
            val requiredEntries = listOf(
                "space/minecraftstl/xyml/library/lwjgl/UnsafeAgent.class",
                "space/minecraftstl/xyml/library/lwjgl/BuildConfig.class",
            )
            requiredEntries.forEach { entry ->
                check(jar.getJarEntry(entry) != null) { "Missing agent entry: $entry" }
            }
            check(jar.entries().asSequence().none { it.name.startsWith("org/glavo/lwjgl/") }) {
                "Agent artifact retains the legacy org.glavo.lwjgl package"
            }

            val attributes = jar.manifest.mainAttributes
            check(attributes.getValue("Premain-Class") == agentClassName) { "Unexpected Premain-Class" }
            check(attributes.getValue("Agent-Class") == agentClassName) { "Unexpected Agent-Class" }
            check(attributes.getValue("Implementation-Version") == project.version.toString()) {
                "Agent manifest does not contain the XYML release version"
            }
            check(attributes.getValue("Lwjgl-Unsafe-Agent-Upstream-Version") == upstreamVersion) {
                "Agent manifest does not record upstream $upstreamVersion"
            }

            val classEntry = jar.getJarEntry(requiredEntries.first())
            DataInputStream(jar.getInputStream(classEntry)).use { input ->
                check(input.readInt() == 0xCAFEBABE.toInt()) { "Invalid class file header" }
                input.readUnsignedShort()
                val majorVersion = input.readUnsignedShort()
                check(majorVersion == 69) { "Agent must use Java 25 bytecode, found major $majorVersion" }
            }
        }
    }
}

tasks.named("checkstyle") {
    dependsOn(verifyAgentLicenseHeaders)
}

tasks.check {
    dependsOn(verifyAgentArtifact, verifyAgentLicenseHeaders)
}
